### model
model_name_or_path: /root/autodl-tmp/qwen_weights
### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 8
freeze_vision_tower: true  # 保持防守策略
### dataset
dataset: Task8_round3
dataset_dir: /root/autodl-tmp/MedSG-Bench/train
template: qwen2_vl
cutoff_len: 2048
max_samples: 100
overwrite_cache: true
preprocessing_num_workers: 8
### output
output_dir: /root/autodl-tmp/MedSG-Bench/train/output_round3
logging_steps: 2
save_steps: 100
plot_loss: true
overwrite_output_dir: true
### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
